[package]
name = "rnote-compose"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# even though all submodule dependencies are specified with their url, cargo will search the root repository for the local packages
# see: https://github.com/rust-lang/cargo/issues/1462

rnote-fileformats = {path = "../rnote-fileformats", version="0.1"}

piet = { git = "https://github.com/flxzt/piet", branch = "rnote" }
#piet = { path = "../piet/piet" }
piet-svg = { git = "https://github.com/flxzt/piet", branch = "rnote" }
#piet-svg = { path = "../piet/piet-svg" }
piet-cairo = { git = "https://github.com/flxzt/piet", branch = "rnote" }
#piet-cairo = { path = "../piet/piet-cairo" }
ink-stroke-modeler-rs = { git = "https://github.com/flxzt/ink-stroke-modeler-rs", branch = "main" }
#ink-stroke-modeler-rs = { path = "../ink-stroke-modeler-rs" }

log = "0.4.16"
pretty_env_logger = "0.4.0"
anyhow = "1.0"
serde = {version = "1.0", features = ["derive"]}
num-derive = "0.3.3"
num-traits = "0.2.14"
rand = "0.8.5"
rand_pcg = "0.3.1"
rand_distr = "0.4.3"
regex = "1.5"
nalgebra = { version = "0.31.0", features = ["serde-serialize"] }
parry2d-f64 = { version = "0.9.0", features = ["serde-serialize"] }
kurbo = "0.8.3"
image = "0.23.14"
svg = "0.10.0"

[dev-dependencies]
