[package]
name = "rnote-compose"
version = "0.1.0"
edition = "2021"
rust-version = "1.65"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ink-stroke-modeler-rs = { git = "https://github.com/flxzt/ink-stroke-modeler-rs", rev = "9d02f080864f6978bb3066fdbe41a1d8c0577953" }

log = "0.4.16"
anyhow = "1.0"
serde = {version = "1.0", features = ["derive"]}
num-derive = "0.3.3"
num-traits = "0.2.14"
rand = "0.8.5"
rand_pcg = "0.3.1"
rand_distr = "0.4.3"
regex = "1.5"
once_cell = "1.8"
nalgebra = { version = "0.31.0", features = ["serde-serialize"] }
parry2d-f64 = { version = "0.9.0", features = ["serde-serialize"] }
piet = "0.6"
piet-cairo = "0.6"
kurbo = "0.9.0"
svg = "0.10.0"
roughr = "0.4.0"
rough_piet = "0.4.0"

[dev-dependencies]
