

[workspace]
members = [
    "rnote-compose",
    "rnote-engine",
    "rnote-ui",
    "rnote-fileformats",
]
exclude = [ "./piet" ]


[profile.dev]
opt-level = 2
debug = true

[profile.release]
opt-level = 3