[workspace]
members = [
    "crates/rnote-compose",
    "crates/rnote-engine",
    "crates/rnote-cli",
    "crates/rnote-ui",
]
resolver = "2"

[workspace.package]
version = "0.9.4"
edition = "2021"
rust-version = "1.70"
authors = ["The Rnote Authors"]
license = "GPL-3.0-or-later"
homepage = "https://rnote.flxzt.net"
repository = "https://github.com/flxzt/rnote"

[workspace.dependencies]
rnote-compose = { version="0.9.4", path = "crates/rnote-compose" }
rnote-engine = { version="0.9.4", path = "crates/rnote-engine" }

tracing = "0.1"
tracing-subscriber = {version = "0.3", features = ["env-filter"] }
anyhow = "1"
thiserror = "1"
approx = "0.5.1"
num-derive = "0.4"
num-traits = "0.2"
itertools = "0.12"
once_cell = "1"
futures = "0.3"
rayon = "1"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
ijson = "0.1"
nalgebra = { version = "0.32", features = ["serde-serialize"] }
parry2d-f64 = { version = "0.13", features = ["serde-serialize"] }
rand = "0.8"
rand_pcg = "0.3"
rand_distr = "0.4"
slotmap = { version = "1", features = ["serde"] }
rstar = "0.11"
geo = "0.27"
flate2 = "1"
chrono = "0.4.31"
base64 = "0.21"
semver = { version = "1", features = ["serde"]}
regex = "1.10"
url = "2"
fs_extra = "1"
same-file = "1"
unicode-segmentation = "1"
roxmltree = "0.19"
xmlwriter = "0.1"
usvg = "0.36"
svg = "0.14"
image = "0.24"
kurbo = "0.9"
piet = "0.6"
piet-cairo = "0.6"
roughr = "0.6"
rough_piet = "0.6"
palette = "0.7.3"
rodio = { version = "0.17", default-features = false, features = ["symphonia-wav"] }
winresource = "0.1"
smol = "1"
clap = { version = "4", features = ["derive"] }
indicatif = "0.17"
dialoguer = "0.11"
open = "5"
atty = "0.2"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
glib = "0.18.3"
glib-build-tools = "0.18.0"
gio = "0.18.3"
cairo-rs = { version = "0.18", features = ["png", "svg", "pdf"] }
librsvg = "2.57"
# newest poppler feature ("v21_12") is causing linking errors when building in mingw for some reason.
poppler-rs = { version = "0.22", features = ["v20_9"] }
gtk4 = { version = "0.7.3", features = ["v4_12"] }
adw = { version = "0.5.3", package="libadwaita", features = ["v1_4"] }
numeric-sort = "0.1"

[patch.crates-io]
# once a new piet (current v0.6.2) is released with the updated cairo, this can be removed
piet = { git = "https://github.com/linebender/piet", rev = "88e8e6c6fe41d8c99e3bccbf3a076b3661c4472a" }
piet-cairo = { git = "https://github.com/linebender/piet", rev = "88e8e6c6fe41d8c99e3bccbf3a076b3661c4472a" }

[profile.dev]
opt-level = 2
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
# We want to be able to debug in the release build as well
debug = true
