

[workspace]
members = [
    "rnote-compose",
    "rnote-engine",
    "rnote-ui",
    "rnote-fileformats",
    "rnote-cli",
]

exclude = [
    "ink-stroke-modeler-rs"
]


[profile.dev]
opt-level = 2
debug = true

[profile.release]
opt-level = 3
