[workspace]
members = [
    "rnote-compose",
    "rnote-fileformats",
    "rnote-engine",
    "rnote-cli",
    "rnote-ui",
]

[profile.dev]
opt-level = 2
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[patch.crates-io]
# once a new piet (current v0.6.2) is released with the updated cairo, this can be removed
piet = {git = "https://github.com/linebender/piet", rev = "413397445e6772e0a651d60cf58a823b98f67c23"}
piet-cairo = {git = "https://github.com/linebender/piet", rev = "413397445e6772e0a651d60cf58a823b98f67c23"}