[workspace]
members = [
    "rnote-compose",
    "rnote-fileformats",
    "rnote-engine",
    "rnote-cli",
    "rnote-ui",
]

[profile.dev]
opt-level = 2
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
