[workspace]
members = [
    "rnote-compose",
    "rnote-fileformats",
    "rnote-engine",
    "rnote-cli",
    "rnote-ui",
]

[profile.dev]
opt-level = 2
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1

[patch.crates-io]
# patched to include bezier curve stroke & hachure fill fixes. Once a new release is out (v0.5) on crates-io this can be removed
roughr = {git = "https://github.com/orhanbalci/rough-rs", rev = "71100d17f87bd9d6dc9081c2681f9ac710fac389" }
rough_piet = {git = "https://github.com/orhanbalci/rough-rs", rev = "71100d17f87bd9d6dc9081c2681f9ac710fac389" }