[workspace]
members = [
    "rnote-compose",
    "rnote-fileformats",
    "rnote-engine",
    "rnote-cli",
    "rnote-ui",
]

[profile.dev]
opt-level = 2
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = true # We want to be able to debug in the release build too 

[patch.crates-io]
# once a new piet (current v0.6.2) is released with the updated cairo, this can be removed
piet = {git = "https://github.com/linebender/piet", rev = "1d8a6fd627d8d6492bc42a42c734205a981077f8"}
piet-cairo = {git = "https://github.com/linebender/piet", rev = "1d8a6fd627d8d6492bc42a42c734205a981077f8"}
