[workspace]
members = [
    "crates/rnote-compose",
    "crates/rnote-engine",
    "crates/rnote-cli",
    "crates/rnote-ui",
]
resolver = "2"

[workspace.package]
authors = ["The Rnote Authors"]
edition = "2021"
homepage = "https://rnote.flxzt.net"
license = "GPL-3.0-or-later"
repository = "https://github.com/flxzt/rnote"
rust-version = "1.70"
version = "0.9.4"

[workspace.dependencies]
rnote-compose = { version = "0.9.4", path = "crates/rnote-compose" }
rnote-engine = { version = "0.9.4", path = "crates/rnote-engine" }

anyhow = "1"
approx = "0.5.1"
atty = "0.2"
base64 = "0.21"
cairo-rs = { version = "0.19.1", features = ["v1_18", "png", "svg", "pdf"] }
chrono = "0.4.33"
clap = { version = "4", features = ["derive"] }
dialoguer = "0.11"
flate2 = "1"
fs_extra = "1"
futures = "0.3"
geo = "0.27"
gettext-rs = { version = "0.7", features = ["gettext-system"] }
gio = "0.19.0"
glib = "0.19.0"
glib-build-tools = "0.19.0"
ijson = "0.1"
image = "0.24"
indicatif = "0.17"
itertools = "0.12"
kurbo = "0.10"
nalgebra = { version = "0.32", features = ["serde-serialize"] }
num-derive = "0.4"
num-traits = "0.2"
once_cell = "1"
open = "5"
palette = "0.7.4"
parry2d-f64 = { version = "0.13", features = ["serde-serialize"] }
piet = "0.6"
piet-cairo = "0.6"
rand = "0.8"
rand_distr = "0.4"
rand_pcg = "0.3"
rayon = "1"
regex = "1.10"
rodio = { version = "0.17", default-features = false, features = [
    "symphonia-wav",
] }
rough_piet = "0.6"
roughr = "0.6"
roxmltree = "0.19"
rstar = "0.12"
same-file = "1"
semver = { version = "1", features = ["serde"] }
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
slotmap = { version = "1", features = ["serde"] }
smol = "2"
svg = "0.15.1"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
unicode-segmentation = "1"
url = "2"
usvg = "0.40"
winresource = "0.1"
xmlwriter = "0.1"
adw = { version = "0.6.0", package = "libadwaita", features = ["v1_4"] }
gtk4 = { version = "0.8.0", features = ["v4_12"] }
# once a new librsvg (current v2.57.1) is released that includes updated cairo,
# this can be replaced by the version on crates-io.
librsvg = { git = "https://gitlab.gnome.org/GNOME/librsvg", rev = "3a497b56fe581ab4fda1a80ac19352bfb91676b6" }
numeric-sort = "0.1"
poppler-rs = { version = "0.23.0", features = ["v22_2"] }

[patch.crates-io]
# once a new piet (current v0.6.2) is released with updated cairo and kurbo deps, this can be removed.
piet = { git = "https://github.com/linebender/piet", rev = "30813def608e74c0fc1a6aaf726bd3f7bf6964c2" }
piet-cairo = { git = "https://github.com/linebender/piet", rev = "30813def608e74c0fc1a6aaf726bd3f7bf6964c2" }

[profile.dev]
debug = true
opt-level = 2

[profile.release]
codegen-units = 1
lto = "fat"
opt-level = 3
# We want to be able to debug in the release build as well
debug = true
