on:
  release:
    types: [published]
  workflow_dispatch:

name: Generate Dist Archive

jobs:
  ci:
    uses: ./.github/workflows/ci.yml
  dist:
    runs-on: ubuntu-22.04
    container: fedora:38
    needs: [ci]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo dnf upgrade --refresh -y
          sudo dnf install -y gcc gcc-c++ clang python3 make cmake meson kernel-devel gtk4-devel libadwaita-devel poppler-glib-devel poppler-data alsa-lib-devel libappstream-glib desktop-file-utils
      - name: Install toolchain
        id: toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup
        run: |
          meson setup --prefix=/usr _mesonbuild
      - name: Run meson dist
        run: meson dist --no-tests -C _mesonbuild
      - name: Upload dist archive (Workflow Artifact)
        uses: actions/upload-artifact@v3
        with:
          name: rnote-dist-archive-artifact
          path: |
            _mesonbuild/meson-dist/rnote-$(echo ${GITHUB_REF_NAME#v}).tar.xz
            _mesonbuild/meson-dist/rnote-$(echo ${GITHUB_REF_NAME#v}).tar.xz.sha256sum
          if-no-files-found: error
      - name: Upload dist archive (Release Asset)
        if: ${{ github.event_name == 'release' }}
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ github.ref_name }} _mesonbuild/meson-dist/rnote-$(echo ${GITHUB_REF_NAME#v}).tar.xz
          gh release upload ${{ github.ref_name }} _mesonbuild/meson-dist/rnote-$(echo ${GITHUB_REF_NAME#v}).tar.xz.sha256sum
